# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1843046f91243e4919287a50a79110d9ccee3ae79e20bacc18e86aaa3692a38962b2056b64c16121dbfae88478c3615e4afae23f519da4c578f0f5d4acacccea

test:
  secret_key_base: 15f1977f0ac2dedbfc621965a5a14a3adc23ae03fb9ff9ebd677dde9236b972b9a266998a2a9e53e0d0680f46e24c5c2831acdb0591bc4d65529ab5e70c175e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
